package com.oxygen.mbgtools.domain;

import com.oxygen.mbgtools.mybatis.bean.Page;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PetTrendsEntityDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pet_trends_entity
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pet_trends_entity
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pet_trends_entity
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pet_trends_entity
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  *  构造查询条件,pet_trends_entity
     */
    public PetTrendsEntityDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  *  设置排序字段,pet_trends_entity
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  *  获取排序字段,pet_trends_entity
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  *  设置过滤重复数据,pet_trends_entity
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  *  是否过滤重复数据,pet_trends_entity
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  *  获取当前的查询条件实例,pet_trends_entity
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  * ,pet_trends_entity
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  * ,pet_trends_entity
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  *  创建一个查询条件,pet_trends_entity
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  *  内部构建查询条件对象,pet_trends_entity
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  *  清除查询条件,pet_trends_entity
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  * ,pet_trends_entity
     *
     * @param page
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table  * ,pet_trends_entity
     */
    public Page getPage() {
        return page;
    }

    /**
     * pet_trends_entity
     * GeneratedCriteria
     * 数据库表：pet_trends_entity
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andImgArryIsNull() {
            addCriterion("img_arry is null");
            return (Criteria) this;
        }

        public Criteria andImgArryIsNotNull() {
            addCriterion("img_arry is not null");
            return (Criteria) this;
        }

        public Criteria andImgArryEqualTo(String value) {
            addCriterion("img_arry =", value, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryNotEqualTo(String value) {
            addCriterion("img_arry <>", value, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryGreaterThan(String value) {
            addCriterion("img_arry >", value, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryGreaterThanOrEqualTo(String value) {
            addCriterion("img_arry >=", value, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryLessThan(String value) {
            addCriterion("img_arry <", value, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryLessThanOrEqualTo(String value) {
            addCriterion("img_arry <=", value, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryLike(String value) {
            addCriterion("img_arry like", value, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryNotLike(String value) {
            addCriterion("img_arry not like", value, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryIn(List<String> values) {
            addCriterion("img_arry in", values, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryNotIn(List<String> values) {
            addCriterion("img_arry not in", values, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryBetween(String value1, String value2) {
            addCriterion("img_arry between", value1, value2, "imgArry");
            return (Criteria) this;
        }

        public Criteria andImgArryNotBetween(String value1, String value2) {
            addCriterion("img_arry not between", value1, value2, "imgArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryIsNull() {
            addCriterion("video_arry is null");
            return (Criteria) this;
        }

        public Criteria andVideoArryIsNotNull() {
            addCriterion("video_arry is not null");
            return (Criteria) this;
        }

        public Criteria andVideoArryEqualTo(String value) {
            addCriterion("video_arry =", value, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryNotEqualTo(String value) {
            addCriterion("video_arry <>", value, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryGreaterThan(String value) {
            addCriterion("video_arry >", value, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryGreaterThanOrEqualTo(String value) {
            addCriterion("video_arry >=", value, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryLessThan(String value) {
            addCriterion("video_arry <", value, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryLessThanOrEqualTo(String value) {
            addCriterion("video_arry <=", value, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryLike(String value) {
            addCriterion("video_arry like", value, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryNotLike(String value) {
            addCriterion("video_arry not like", value, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryIn(List<String> values) {
            addCriterion("video_arry in", values, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryNotIn(List<String> values) {
            addCriterion("video_arry not in", values, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryBetween(String value1, String value2) {
            addCriterion("video_arry between", value1, value2, "videoArry");
            return (Criteria) this;
        }

        public Criteria andVideoArryNotBetween(String value1, String value2) {
            addCriterion("video_arry not between", value1, value2, "videoArry");
            return (Criteria) this;
        }

        public Criteria andFileTypeIsNull() {
            addCriterion("file_type is null");
            return (Criteria) this;
        }

        public Criteria andFileTypeIsNotNull() {
            addCriterion("file_type is not null");
            return (Criteria) this;
        }

        public Criteria andFileTypeEqualTo(Byte value) {
            addCriterion("file_type =", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotEqualTo(Byte value) {
            addCriterion("file_type <>", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeGreaterThan(Byte value) {
            addCriterion("file_type >", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("file_type >=", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLessThan(Byte value) {
            addCriterion("file_type <", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLessThanOrEqualTo(Byte value) {
            addCriterion("file_type <=", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeIn(List<Byte> values) {
            addCriterion("file_type in", values, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotIn(List<Byte> values) {
            addCriterion("file_type not in", values, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeBetween(Byte value1, Byte value2) {
            addCriterion("file_type between", value1, value2, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("file_type not between", value1, value2, "fileType");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLocsIsNull() {
            addCriterion("locs is null");
            return (Criteria) this;
        }

        public Criteria andLocsIsNotNull() {
            addCriterion("locs is not null");
            return (Criteria) this;
        }

        public Criteria andLocsEqualTo(String value) {
            addCriterion("locs =", value, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsNotEqualTo(String value) {
            addCriterion("locs <>", value, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsGreaterThan(String value) {
            addCriterion("locs >", value, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsGreaterThanOrEqualTo(String value) {
            addCriterion("locs >=", value, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsLessThan(String value) {
            addCriterion("locs <", value, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsLessThanOrEqualTo(String value) {
            addCriterion("locs <=", value, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsLike(String value) {
            addCriterion("locs like", value, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsNotLike(String value) {
            addCriterion("locs not like", value, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsIn(List<String> values) {
            addCriterion("locs in", values, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsNotIn(List<String> values) {
            addCriterion("locs not in", values, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsBetween(String value1, String value2) {
            addCriterion("locs between", value1, value2, "locs");
            return (Criteria) this;
        }

        public Criteria andLocsNotBetween(String value1, String value2) {
            addCriterion("locs not between", value1, value2, "locs");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Boolean value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Boolean value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Boolean value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Boolean value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Boolean> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Boolean> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeIsNull() {
            addCriterion("like_pet_type is null");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeIsNotNull() {
            addCriterion("like_pet_type is not null");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeEqualTo(Boolean value) {
            addCriterion("like_pet_type =", value, "likePetType");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeNotEqualTo(Boolean value) {
            addCriterion("like_pet_type <>", value, "likePetType");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeGreaterThan(Boolean value) {
            addCriterion("like_pet_type >", value, "likePetType");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("like_pet_type >=", value, "likePetType");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeLessThan(Boolean value) {
            addCriterion("like_pet_type <", value, "likePetType");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("like_pet_type <=", value, "likePetType");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeIn(List<Boolean> values) {
            addCriterion("like_pet_type in", values, "likePetType");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeNotIn(List<Boolean> values) {
            addCriterion("like_pet_type not in", values, "likePetType");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("like_pet_type between", value1, value2, "likePetType");
            return (Criteria) this;
        }

        public Criteria andLikePetTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("like_pet_type not between", value1, value2, "likePetType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andShareCountIsNull() {
            addCriterion("share_count is null");
            return (Criteria) this;
        }

        public Criteria andShareCountIsNotNull() {
            addCriterion("share_count is not null");
            return (Criteria) this;
        }

        public Criteria andShareCountEqualTo(Integer value) {
            addCriterion("share_count =", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountNotEqualTo(Integer value) {
            addCriterion("share_count <>", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountGreaterThan(Integer value) {
            addCriterion("share_count >", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("share_count >=", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountLessThan(Integer value) {
            addCriterion("share_count <", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountLessThanOrEqualTo(Integer value) {
            addCriterion("share_count <=", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountIn(List<Integer> values) {
            addCriterion("share_count in", values, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountNotIn(List<Integer> values) {
            addCriterion("share_count not in", values, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountBetween(Integer value1, Integer value2) {
            addCriterion("share_count between", value1, value2, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountNotBetween(Integer value1, Integer value2) {
            addCriterion("share_count not between", value1, value2, "shareCount");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlIsNull() {
            addCriterion("head_pcI_mg_url is null");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlIsNotNull() {
            addCriterion("head_pcI_mg_url is not null");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlEqualTo(String value) {
            addCriterion("head_pcI_mg_url =", value, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlNotEqualTo(String value) {
            addCriterion("head_pcI_mg_url <>", value, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlGreaterThan(String value) {
            addCriterion("head_pcI_mg_url >", value, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("head_pcI_mg_url >=", value, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlLessThan(String value) {
            addCriterion("head_pcI_mg_url <", value, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlLessThanOrEqualTo(String value) {
            addCriterion("head_pcI_mg_url <=", value, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlLike(String value) {
            addCriterion("head_pcI_mg_url like", value, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlNotLike(String value) {
            addCriterion("head_pcI_mg_url not like", value, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlIn(List<String> values) {
            addCriterion("head_pcI_mg_url in", values, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlNotIn(List<String> values) {
            addCriterion("head_pcI_mg_url not in", values, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlBetween(String value1, String value2) {
            addCriterion("head_pcI_mg_url between", value1, value2, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andHeadPciMgUrlNotBetween(String value1, String value2) {
            addCriterion("head_pcI_mg_url not between", value1, value2, "headPciMgUrl");
            return (Criteria) this;
        }

        public Criteria andNickMameIsNull() {
            addCriterion("nick_mame is null");
            return (Criteria) this;
        }

        public Criteria andNickMameIsNotNull() {
            addCriterion("nick_mame is not null");
            return (Criteria) this;
        }

        public Criteria andNickMameEqualTo(String value) {
            addCriterion("nick_mame =", value, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameNotEqualTo(String value) {
            addCriterion("nick_mame <>", value, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameGreaterThan(String value) {
            addCriterion("nick_mame >", value, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameGreaterThanOrEqualTo(String value) {
            addCriterion("nick_mame >=", value, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameLessThan(String value) {
            addCriterion("nick_mame <", value, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameLessThanOrEqualTo(String value) {
            addCriterion("nick_mame <=", value, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameLike(String value) {
            addCriterion("nick_mame like", value, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameNotLike(String value) {
            addCriterion("nick_mame not like", value, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameIn(List<String> values) {
            addCriterion("nick_mame in", values, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameNotIn(List<String> values) {
            addCriterion("nick_mame not in", values, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameBetween(String value1, String value2) {
            addCriterion("nick_mame between", value1, value2, "nickMame");
            return (Criteria) this;
        }

        public Criteria andNickMameNotBetween(String value1, String value2) {
            addCriterion("nick_mame not between", value1, value2, "nickMame");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andSignNameIsNull() {
            addCriterion("sign_name is null");
            return (Criteria) this;
        }

        public Criteria andSignNameIsNotNull() {
            addCriterion("sign_name is not null");
            return (Criteria) this;
        }

        public Criteria andSignNameEqualTo(String value) {
            addCriterion("sign_name =", value, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameNotEqualTo(String value) {
            addCriterion("sign_name <>", value, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameGreaterThan(String value) {
            addCriterion("sign_name >", value, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameGreaterThanOrEqualTo(String value) {
            addCriterion("sign_name >=", value, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameLessThan(String value) {
            addCriterion("sign_name <", value, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameLessThanOrEqualTo(String value) {
            addCriterion("sign_name <=", value, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameLike(String value) {
            addCriterion("sign_name like", value, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameNotLike(String value) {
            addCriterion("sign_name not like", value, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameIn(List<String> values) {
            addCriterion("sign_name in", values, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameNotIn(List<String> values) {
            addCriterion("sign_name not in", values, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameBetween(String value1, String value2) {
            addCriterion("sign_name between", value1, value2, "signName");
            return (Criteria) this;
        }

        public Criteria andSignNameNotBetween(String value1, String value2) {
            addCriterion("sign_name not between", value1, value2, "signName");
            return (Criteria) this;
        }

        public Criteria andDistanceIsNull() {
            addCriterion("distance is null");
            return (Criteria) this;
        }

        public Criteria andDistanceIsNotNull() {
            addCriterion("distance is not null");
            return (Criteria) this;
        }

        public Criteria andDistanceEqualTo(Double value) {
            addCriterion("distance =", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotEqualTo(Double value) {
            addCriterion("distance <>", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceGreaterThan(Double value) {
            addCriterion("distance >", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceGreaterThanOrEqualTo(Double value) {
            addCriterion("distance >=", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLessThan(Double value) {
            addCriterion("distance <", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLessThanOrEqualTo(Double value) {
            addCriterion("distance <=", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceIn(List<Double> values) {
            addCriterion("distance in", values, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotIn(List<Double> values) {
            addCriterion("distance not in", values, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceBetween(Double value1, Double value2) {
            addCriterion("distance between", value1, value2, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotBetween(Double value1, Double value2) {
            addCriterion("distance not between", value1, value2, "distance");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusIsNull() {
            addCriterion("upvote_status is null");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusIsNotNull() {
            addCriterion("upvote_status is not null");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusEqualTo(Boolean value) {
            addCriterion("upvote_status =", value, "upvoteStatus");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusNotEqualTo(Boolean value) {
            addCriterion("upvote_status <>", value, "upvoteStatus");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusGreaterThan(Boolean value) {
            addCriterion("upvote_status >", value, "upvoteStatus");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("upvote_status >=", value, "upvoteStatus");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusLessThan(Boolean value) {
            addCriterion("upvote_status <", value, "upvoteStatus");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("upvote_status <=", value, "upvoteStatus");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusIn(List<Boolean> values) {
            addCriterion("upvote_status in", values, "upvoteStatus");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusNotIn(List<Boolean> values) {
            addCriterion("upvote_status not in", values, "upvoteStatus");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("upvote_status between", value1, value2, "upvoteStatus");
            return (Criteria) this;
        }

        public Criteria andUpvoteStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("upvote_status not between", value1, value2, "upvoteStatus");
            return (Criteria) this;
        }

        public Criteria andFollowStatusIsNull() {
            addCriterion("follow_status is null");
            return (Criteria) this;
        }

        public Criteria andFollowStatusIsNotNull() {
            addCriterion("follow_status is not null");
            return (Criteria) this;
        }

        public Criteria andFollowStatusEqualTo(Byte value) {
            addCriterion("follow_status =", value, "followStatus");
            return (Criteria) this;
        }

        public Criteria andFollowStatusNotEqualTo(Byte value) {
            addCriterion("follow_status <>", value, "followStatus");
            return (Criteria) this;
        }

        public Criteria andFollowStatusGreaterThan(Byte value) {
            addCriterion("follow_status >", value, "followStatus");
            return (Criteria) this;
        }

        public Criteria andFollowStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("follow_status >=", value, "followStatus");
            return (Criteria) this;
        }

        public Criteria andFollowStatusLessThan(Byte value) {
            addCriterion("follow_status <", value, "followStatus");
            return (Criteria) this;
        }

        public Criteria andFollowStatusLessThanOrEqualTo(Byte value) {
            addCriterion("follow_status <=", value, "followStatus");
            return (Criteria) this;
        }

        public Criteria andFollowStatusIn(List<Byte> values) {
            addCriterion("follow_status in", values, "followStatus");
            return (Criteria) this;
        }

        public Criteria andFollowStatusNotIn(List<Byte> values) {
            addCriterion("follow_status not in", values, "followStatus");
            return (Criteria) this;
        }

        public Criteria andFollowStatusBetween(Byte value1, Byte value2) {
            addCriterion("follow_status between", value1, value2, "followStatus");
            return (Criteria) this;
        }

        public Criteria andFollowStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("follow_status not between", value1, value2, "followStatus");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNull() {
            addCriterion("comment_count is null");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNotNull() {
            addCriterion("comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCountEqualTo(Integer value) {
            addCriterion("comment_count =", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotEqualTo(Integer value) {
            addCriterion("comment_count <>", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThan(Integer value) {
            addCriterion("comment_count >", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_count >=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThan(Integer value) {
            addCriterion("comment_count <", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThanOrEqualTo(Integer value) {
            addCriterion("comment_count <=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountIn(List<Integer> values) {
            addCriterion("comment_count in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotIn(List<Integer> values) {
            addCriterion("comment_count not in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountBetween(Integer value1, Integer value2) {
            addCriterion("comment_count between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_count not between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Boolean value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Boolean value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Boolean value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Boolean value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Boolean value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Boolean> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Boolean> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Boolean value1, Boolean value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Byte value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Byte value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Byte value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Byte value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Byte value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Byte> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Byte> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Byte value1, Byte value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditReasonIsNull() {
            addCriterion("audit_reason is null");
            return (Criteria) this;
        }

        public Criteria andAuditReasonIsNotNull() {
            addCriterion("audit_reason is not null");
            return (Criteria) this;
        }

        public Criteria andAuditReasonEqualTo(String value) {
            addCriterion("audit_reason =", value, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonNotEqualTo(String value) {
            addCriterion("audit_reason <>", value, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonGreaterThan(String value) {
            addCriterion("audit_reason >", value, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonGreaterThanOrEqualTo(String value) {
            addCriterion("audit_reason >=", value, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonLessThan(String value) {
            addCriterion("audit_reason <", value, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonLessThanOrEqualTo(String value) {
            addCriterion("audit_reason <=", value, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonLike(String value) {
            addCriterion("audit_reason like", value, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonNotLike(String value) {
            addCriterion("audit_reason not like", value, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonIn(List<String> values) {
            addCriterion("audit_reason in", values, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonNotIn(List<String> values) {
            addCriterion("audit_reason not in", values, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonBetween(String value1, String value2) {
            addCriterion("audit_reason between", value1, value2, "auditReason");
            return (Criteria) this;
        }

        public Criteria andAuditReasonNotBetween(String value1, String value2) {
            addCriterion("audit_reason not between", value1, value2, "auditReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonIsNull() {
            addCriterion("down_reason is null");
            return (Criteria) this;
        }

        public Criteria andDownReasonIsNotNull() {
            addCriterion("down_reason is not null");
            return (Criteria) this;
        }

        public Criteria andDownReasonEqualTo(String value) {
            addCriterion("down_reason =", value, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonNotEqualTo(String value) {
            addCriterion("down_reason <>", value, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonGreaterThan(String value) {
            addCriterion("down_reason >", value, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonGreaterThanOrEqualTo(String value) {
            addCriterion("down_reason >=", value, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonLessThan(String value) {
            addCriterion("down_reason <", value, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonLessThanOrEqualTo(String value) {
            addCriterion("down_reason <=", value, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonLike(String value) {
            addCriterion("down_reason like", value, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonNotLike(String value) {
            addCriterion("down_reason not like", value, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonIn(List<String> values) {
            addCriterion("down_reason in", values, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonNotIn(List<String> values) {
            addCriterion("down_reason not in", values, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonBetween(String value1, String value2) {
            addCriterion("down_reason between", value1, value2, "downReason");
            return (Criteria) this;
        }

        public Criteria andDownReasonNotBetween(String value1, String value2) {
            addCriterion("down_reason not between", value1, value2, "downReason");
            return (Criteria) this;
        }

        public Criteria andZanCountIsNull() {
            addCriterion("zan_count is null");
            return (Criteria) this;
        }

        public Criteria andZanCountIsNotNull() {
            addCriterion("zan_count is not null");
            return (Criteria) this;
        }

        public Criteria andZanCountEqualTo(Integer value) {
            addCriterion("zan_count =", value, "zanCount");
            return (Criteria) this;
        }

        public Criteria andZanCountNotEqualTo(Integer value) {
            addCriterion("zan_count <>", value, "zanCount");
            return (Criteria) this;
        }

        public Criteria andZanCountGreaterThan(Integer value) {
            addCriterion("zan_count >", value, "zanCount");
            return (Criteria) this;
        }

        public Criteria andZanCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("zan_count >=", value, "zanCount");
            return (Criteria) this;
        }

        public Criteria andZanCountLessThan(Integer value) {
            addCriterion("zan_count <", value, "zanCount");
            return (Criteria) this;
        }

        public Criteria andZanCountLessThanOrEqualTo(Integer value) {
            addCriterion("zan_count <=", value, "zanCount");
            return (Criteria) this;
        }

        public Criteria andZanCountIn(List<Integer> values) {
            addCriterion("zan_count in", values, "zanCount");
            return (Criteria) this;
        }

        public Criteria andZanCountNotIn(List<Integer> values) {
            addCriterion("zan_count not in", values, "zanCount");
            return (Criteria) this;
        }

        public Criteria andZanCountBetween(Integer value1, Integer value2) {
            addCriterion("zan_count between", value1, value2, "zanCount");
            return (Criteria) this;
        }

        public Criteria andZanCountNotBetween(Integer value1, Integer value2) {
            addCriterion("zan_count not between", value1, value2, "zanCount");
            return (Criteria) this;
        }

        public Criteria andAdopterIdIsNull() {
            addCriterion("adopter_id is null");
            return (Criteria) this;
        }

        public Criteria andAdopterIdIsNotNull() {
            addCriterion("adopter_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdopterIdEqualTo(Long value) {
            addCriterion("adopter_id =", value, "adopterId");
            return (Criteria) this;
        }

        public Criteria andAdopterIdNotEqualTo(Long value) {
            addCriterion("adopter_id <>", value, "adopterId");
            return (Criteria) this;
        }

        public Criteria andAdopterIdGreaterThan(Long value) {
            addCriterion("adopter_id >", value, "adopterId");
            return (Criteria) this;
        }

        public Criteria andAdopterIdGreaterThanOrEqualTo(Long value) {
            addCriterion("adopter_id >=", value, "adopterId");
            return (Criteria) this;
        }

        public Criteria andAdopterIdLessThan(Long value) {
            addCriterion("adopter_id <", value, "adopterId");
            return (Criteria) this;
        }

        public Criteria andAdopterIdLessThanOrEqualTo(Long value) {
            addCriterion("adopter_id <=", value, "adopterId");
            return (Criteria) this;
        }

        public Criteria andAdopterIdIn(List<Long> values) {
            addCriterion("adopter_id in", values, "adopterId");
            return (Criteria) this;
        }

        public Criteria andAdopterIdNotIn(List<Long> values) {
            addCriterion("adopter_id not in", values, "adopterId");
            return (Criteria) this;
        }

        public Criteria andAdopterIdBetween(Long value1, Long value2) {
            addCriterion("adopter_id between", value1, value2, "adopterId");
            return (Criteria) this;
        }

        public Criteria andAdopterIdNotBetween(Long value1, Long value2) {
            addCriterion("adopter_id not between", value1, value2, "adopterId");
            return (Criteria) this;
        }

        public Criteria andApplicateCountIsNull() {
            addCriterion("applicate_count is null");
            return (Criteria) this;
        }

        public Criteria andApplicateCountIsNotNull() {
            addCriterion("applicate_count is not null");
            return (Criteria) this;
        }

        public Criteria andApplicateCountEqualTo(Integer value) {
            addCriterion("applicate_count =", value, "applicateCount");
            return (Criteria) this;
        }

        public Criteria andApplicateCountNotEqualTo(Integer value) {
            addCriterion("applicate_count <>", value, "applicateCount");
            return (Criteria) this;
        }

        public Criteria andApplicateCountGreaterThan(Integer value) {
            addCriterion("applicate_count >", value, "applicateCount");
            return (Criteria) this;
        }

        public Criteria andApplicateCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("applicate_count >=", value, "applicateCount");
            return (Criteria) this;
        }

        public Criteria andApplicateCountLessThan(Integer value) {
            addCriterion("applicate_count <", value, "applicateCount");
            return (Criteria) this;
        }

        public Criteria andApplicateCountLessThanOrEqualTo(Integer value) {
            addCriterion("applicate_count <=", value, "applicateCount");
            return (Criteria) this;
        }

        public Criteria andApplicateCountIn(List<Integer> values) {
            addCriterion("applicate_count in", values, "applicateCount");
            return (Criteria) this;
        }

        public Criteria andApplicateCountNotIn(List<Integer> values) {
            addCriterion("applicate_count not in", values, "applicateCount");
            return (Criteria) this;
        }

        public Criteria andApplicateCountBetween(Integer value1, Integer value2) {
            addCriterion("applicate_count between", value1, value2, "applicateCount");
            return (Criteria) this;
        }

        public Criteria andApplicateCountNotBetween(Integer value1, Integer value2) {
            addCriterion("applicate_count not between", value1, value2, "applicateCount");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusIsNull() {
            addCriterion("apply_adopt_status is null");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusIsNotNull() {
            addCriterion("apply_adopt_status is not null");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusEqualTo(Boolean value) {
            addCriterion("apply_adopt_status =", value, "applyAdoptStatus");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusNotEqualTo(Boolean value) {
            addCriterion("apply_adopt_status <>", value, "applyAdoptStatus");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusGreaterThan(Boolean value) {
            addCriterion("apply_adopt_status >", value, "applyAdoptStatus");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("apply_adopt_status >=", value, "applyAdoptStatus");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusLessThan(Boolean value) {
            addCriterion("apply_adopt_status <", value, "applyAdoptStatus");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("apply_adopt_status <=", value, "applyAdoptStatus");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusIn(List<Boolean> values) {
            addCriterion("apply_adopt_status in", values, "applyAdoptStatus");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusNotIn(List<Boolean> values) {
            addCriterion("apply_adopt_status not in", values, "applyAdoptStatus");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("apply_adopt_status between", value1, value2, "applyAdoptStatus");
            return (Criteria) this;
        }

        public Criteria andApplyAdoptStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("apply_adopt_status not between", value1, value2, "applyAdoptStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andOUserIdIsNull() {
            addCriterion("o_user_id is null");
            return (Criteria) this;
        }

        public Criteria andOUserIdIsNotNull() {
            addCriterion("o_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andOUserIdEqualTo(String value) {
            addCriterion("o_user_id =", value, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdNotEqualTo(String value) {
            addCriterion("o_user_id <>", value, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdGreaterThan(String value) {
            addCriterion("o_user_id >", value, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("o_user_id >=", value, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdLessThan(String value) {
            addCriterion("o_user_id <", value, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdLessThanOrEqualTo(String value) {
            addCriterion("o_user_id <=", value, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdLike(String value) {
            addCriterion("o_user_id like", value, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdNotLike(String value) {
            addCriterion("o_user_id not like", value, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdIn(List<String> values) {
            addCriterion("o_user_id in", values, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdNotIn(List<String> values) {
            addCriterion("o_user_id not in", values, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdBetween(String value1, String value2) {
            addCriterion("o_user_id between", value1, value2, "oUserId");
            return (Criteria) this;
        }

        public Criteria andOUserIdNotBetween(String value1, String value2) {
            addCriterion("o_user_id not between", value1, value2, "oUserId");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：pet_trends_entity
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * pet_trends_entity
     * Criterion
     * 数据库表：pet_trends_entity
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}